# Site settings
title: VMware Validated Designs
description: 'IT Automation Cloud 1.0'
url: 'http://underanalyzed.com/vvd/'
baseurl: '/vvd/'

author:
  name: 'VMware'
  email: sddc-tm@vmware.com
  twitter_username: vmwaresddc

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
