# Setup
title:              Morning Hypertext Fragments
description:        All Things Under Analyzed
owner:              Ryan Johnson
header-img:         img/home-bg.jpg
email:              ryan@tenthirtyam.org
baseurl:            
url:                http://tenthirtyam.org
paginate:           1

# Author
author:
  name:             Ryan Johnson
  url:              https://twitter.com/tenthirtyam
  email:            ryan@tenthirtyam.org
  github:           tenthirtyam
  twitter:          tenthirtyam
  linkedin:         tenthirtyam

# Dependancies
markdown:           kramdown
highlighter:        pygments

# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:month/:day/:title/
#relative_permalinks: true

# Exclude Ruby gem stuff
exclude:            ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Gems
#gems:
#  - jekyll-redirect-from
#  - jekyll-sitemap